apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-25T16:56:00Z"
  labels:
    istio-demo: order-api-svc
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:istio-demo: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: rancher
    operation: Update
    time: "2022-11-25T16:56:00Z"
  name: order-api
  namespace: istio-demo
spec:
  clusterIP: 10.43.165.23
  clusterIPs:
  - 10.43.165.23
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: order-api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    istio-demo: order-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
