apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-25T16:57:51Z"
  labels:
    istio-demo: user-server-svc
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:istio-demo: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8003,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: rancher
    operation: Update
    time: "2022-11-25T16:57:51Z"
  name: user-server
  namespace: istio-demo
spec:
  clusterIP: 10.43.6.44
  clusterIPs:
  - 10.43.6.44
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: user-server
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    istio-demo: user-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
