apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
  creationTimestamp: "2022-11-25T14:52:31Z"
  generation: 16
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-istio-demo-order-api
  name: order-api
  namespace: istio-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-istio-demo-order-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-11-29T10:47:31Z"
      creationTimestamp: null
      labels:
        istio-demo: order-api
        workload.user.cattle.io/workloadselector: apps.deployment-istio-demo-order-api
    spec:
      affinity: {}
      containers:
      - env:
        - name: JAEGER_PROPAGATION
          value: order
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc:14268/api/traces
        - name: JAEGER_PROPAGATION
          value: b3
        image: registry.cn-guangzhou.aliyuncs.com/likyam_docker/order-api:v1.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: order-api
        ports:
        - containerPort: 80
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aliyuncs
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-11-25T14:52:31Z"
    lastUpdateTime: "2022-11-29T10:47:42Z"
    message: ReplicaSet "order-api-5746f7f66" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-12-07T07:00:09Z"
    lastUpdateTime: "2022-12-07T07:00:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
